name: tesi-env

dependencies:
  - python=3.10.13
  - pip
  - numpy
  - pandas
  - polars
  - pyspark
  - mmh3
  - tqdm
  - nltk
  - pip:
    - matplotlib
    - psycopg
    - pymongo
    - timeout_decorator
    - bitarray
    - datasketch
    - fasttext
    - compress-fasttext
    - faiss
    - numerize-denumerize
    - orjson