name: nanni-env

dependencies:
  - python=3.10.13
  - pip
  - numpy
  - pandas
  - polars
  - pyspark
  - mmh3
  - tqdm
  - nltk
  - psycopg
  - jsonlines
  - pymongo
  # - timeout_decorator
  # - bitarray
  # - datasketch