name: dltfenv

dependencies:
  - python=3.10.13
  - pip
  - numpy
  - pandas
  - pyspark
  - mmh3
  - tqdm
  - nltk
  - pip:
    - polars
    - bidict
    - tabulate
    - ipykernel
    - matplotlib
    - scikit-learn
    
    - bitarray
    - fasttext
    - datasketch
    - faiss-cpu # that's the basic installation for the CPU-only version
    - wrapt_timeout_decorator # different timeout for sloth
    - efficient-apriori # just for MATE testing

    # DuckDB is used just for testing MATE
    # and could be replaced with Postgres
    - duckdb=1.1.3
    - duckdb_engine=0.15.0
    - pymongo
    - psycopg2
    - sqlalchemy=2.0

    # these are used just for the demo interface
    - pyside6
    - gtk3
    - gobject-introspection
    - adwaita-icon-theme
