name: dltfenv

dependencies:
  - python=3.10.13
  - pip
  - numpy
  - pandas
  - polars
  - pyspark
  - mmh3
  - tqdm
  - nltk
  - pip:
    - bidict
    - matplotlib
    - sqlalchemy
    - pymongo
    - timeout_decorator
    - bitarray
    - datasketch
    - fasttext
    - compress-fasttext
    - faiss
