name: dltfenv

dependencies:
  - python=3.10.13
  - pip
  - numpy
  - pandas
  - pyspark
  - mmh3
  - tqdm
  - nltk
  - pip:
    - pyside6
    - ipykernel
    - tabulate
    - polars
    - psycopg2
    - scikit-learn
    - bidict
    - matplotlib
    - sqlalchemy
    - pymongo
    - bitarray
    - datasketch
    - fasttext
    - faiss-cpu # that's the basic installation for the CPU-only version
    - efficient-apriori # just for MATE testing
    - wrapt_timeout_decorator # different timeout for sloth
    # these are used just for the demo interface
    - gtk3
    - gobject-introspection
    - adwaita-icon-theme
