name: dltfenv

dependencies:
  - python=3.10.13
  - pip
  - numpy
  - pandas
  - pyspark
  - mmh3
  - tqdm
  - nltk
  - pip:
    - pyside6
    - ipykernel
    - tabulate
    - polars
    - psycopg2
    - scikit-learn
    - bidict
    - matplotlib
    - sqlalchemy
    - pymongo
    - timeout_decorator
    - bitarray
    - datasketch
    - fasttext
    - compress-fasttext
    - faiss-cpu # that's the basic installation for the CPU-only version
    - efficient-apriori # just for MATE testing
