name: nanni-env

dependencies:
  - python=3.10.13
  - pip
  - numpy
  - pandas
  - polars
  - pyspark
  - mmh3
  - tqdm
  - nltk
  - psycopg
  - jsonlines
  - pymongo
  -pip:
    - timeout_decorator
    - bitarray
    - datasketch
    - fasttext
    - compress-fasttext
    - faiss